version: '2'
services:
  redis:
    restart: always
    image: redis
    volumes:
      - ./data:/data/
    container_name: redis
    command: redis-server --appendonly yes --protected-mode no --save 60 1
  frontend:
    restart: always
    build: ./canarytokens/
    image: thinkst/canarytokens
    links:
      - redis
    env_file:
      - frontend.env
    volumes:
      - ./uploads:/uploads/
      - ./logs:/logs
    container_name: frontend
    command: bash -c "rm frontend.pid; twistd -noy frontend.tac --logger log.logger --pidfile=frontend.pid"
  switchboard:
    build: ./canarytokens/
    restart: always
    image: thinkst/canarytokens
    ports:
      - "53:53"
      - "53:53/udp"
      - "587:25"
    links:
      - redis
    env_file:
      - switchboard.env
    volumes_from:
      - frontend
    container_name: switchboard
    command: bash -c "rm switchboard.pid; twistd -noy switchboard.tac --logger log.logger --pidfile=switchboard.pid"
  nginx:
    image: nginx:stable
    build: ./certbot-nginx/
    restart: always
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    links:
      - frontend
      - switchboard
    container_name: nginx
    env_file:
      - certbot.env
